model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 16
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 16
      resolution: 384     # to match the aspect
      in_channels: 1
      oout_channels: 1
      ch: 64
      ch_mult: [1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 1
      attn_resolutions: []
      attn_type: "linear"
      dropout: 0.0

# switching to use the manifest data loader
data:
  target: main2.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 0  # crashing becuase of workers?
    wrap: true
    train:
      target: ldm.data.cnt_imagenet.CNTManifest
      params:
        manifest: /work/hdd/bdxf/nstjohn/in-situ_crop/insitu_train.jsonl
        paths: null
        size: [384, 576]
        resize_mode: keep_aspect
        random_crop: false
        random_flip: true
        return_meta: false
        class_key: class_id
        porosity_key: porosity_frac
    validation:
      target: ldm.data.cnt_imagenet.CNTManifest
      params:
        manifest: /work/hdd/bdxf/nstjohn/in-situ_crop/insitu_val.jsonl
        paths: null
        size: [384, 576]
        resize_mode: keep_aspect
        random_crop: false
        return_meta: false
        class_key: class_id
        porosity_key: porosity_frac
  
lightning:
  callbacks:
    image_logger:
      target: main2.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    gpus: 1
    precision: 32
    benchmark: true
    accumulate_grad_batches: 6