# dmr_ACCESS.yaml
model:
  base_learning_rate: 4.5e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    # Diffusion schedule 
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    image_size: 64
    channels: 16
    cond_stage_trainable: True
    concat_mode: False
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    # ---- UNet (make sure channels match AE latents = 8) ----
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_checkpoint: false
        image_size: 64              # ignored at train time
        in_channels: 16              # = AE z_channels
        out_channels: 16             # usually same as in_channels
        model_channels: 192         # OK start; use whatever you trained before
        # changed to [16,8,4] to advoid patchyness
        attention_resolutions: [16,8,4]  # changed from [ 4, 2, 1] to make larger image generation easier
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        use_scale_shift_norm: true
        resblock_updown: true
        use_new_attention_order: false

        # addidtions to make the UNET see conditional
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 128
        num_heads: 8

    # Autoencoder - params from /work/hdd/bdxf/nstjohn/ldmlog/ae/2026-02-23T11-43-36_autoencoder_ACCESS/configs/2026-02-23T11-43-36-project.yaml
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        ckpt_path: /work/hdd/bdxf/nstjohn/ae/insitu/2026-03-03T18-41-00_autoencoder_ACCESS/checkpoints/last.ckpt
        monitor: val/rec_loss
        embed_dim: 16
        lossconfig:
          target: ldm.modules.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 1.0e-06
            disc_weight: 0.5
        ddconfig:
          double_z: true
          z_channels: 16
          resolution: 384
          in_channels: 3
          out_ch: 3
          ch: 64
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 1
          attn_resolutions: []
          attn_type: linear
          dropout: 0.0

    # ---- Class conditioning (class_id) ----
    cond_stage_key: class_id
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        n_classes: 7
        embed_dim: 128
        key: class_id
    conditioning_key: crossattn

    # ---- Strain conditioning (strain_frac) ----
    # cond_stage_key: strain_frac
    # cond_stage_config:
    #   target: ldm.modules.encoders.modules.StrainEmbedder
    #   params:
    #     # n_classes: 6
    #     embed_dim: 128
    #     key: strain_frac
    # conditioning_key: crossattn

data:
  target: main2.DataModuleFromConfig
  params:
    batch_size: 12
    num_workers: 6          # add this
    wrap: true
    train:
      target: ldm.data.cnt_imagenet.CNTManifest
      params:
        manifest: /work/hdd/bdxf/nstjohn/in-situ_crop/insitu_train.jsonl
        size: [ 384 , 576 ]
        random_crop: false
        return_meta: false
        random_flip: true
        resize_mode: keep_aspect
        class_key: class_id
        # strain_class: strain_frac
        # porosity_key: porosity_frac
    validation:
      target: ldm.data.cnt_imagenet.CNTManifest
      params:
        manifest: /work/hdd/bdxf/nstjohn/in-situ_crop/insitu_val.jsonl
        size: [ 384 , 576 ]
        random_crop: false # don't crop the validation
        return_meta: false
        resize_mode:  keep_aspect
        class_key: class_id
        # strain_class: strain_frac
        # porosity_key: porosity_frac




lightning:
  callbacks:
    image_logger:
      target: main2.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True
        
        # for class outputs
        # sample_classes: [0,1,2,3,4,5]
        # n_per_class: 4


  trainer:
    gpus: 1
    precision: 32
    benchmark: true
    accumulate_grad_batches: 6

